spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/lexiflow
    username: lexiflow
    password: lexiflow
  flyway:
    enabled: true
    locations: classpath:db/migration
  data:
    redis:
      host: localhost
      port: ${REDIS_PORT:7379}
      password: lexiflow
  rabbitmq:
    host: localhost
    port: 5672
    username: lexiflow
    password: lexiflow

logging:
  level:
    com.example.lexiflow: INFO
